// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package recipes

import (
	"fmt"
	"strings"
)

// render writes a recipe as YAML, with the comments a person needs to edit it.
//
// Generated by hand rather than by marshalling a struct: a marshalled recipe
// loses the comments, and the comments are most of what makes a scaffold
// worth having over an empty file.
func render(opts NewOptions) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n#\n", title(opts))
	b.WriteString("# Recipes name real-world gear, never Line 6 model IDs. " +
		"\"Ampeg SVT\"\n")
	b.WriteString("# resolves through the gear map, so this file stays " +
		"readable, stays correct\n")
	b.WriteString("# when Line 6 rename something, and works for any Helix " +
		"device.\n#\n")
	b.WriteString("# See docs/recipes.md.\n\n")

	fmt.Fprintf(&b, "id: %s\nkind: artist\nname: %s\n", opts.ID, opts.Name)

	if opts.Band != "" {
		fmt.Fprintf(&b, "band: %s\n", opts.Band)
	}

	fmt.Fprintf(&b, "instrument_type: %s\n\n", opts.Instrument)

	b.WriteString("# The stable layer: career-long, and the part nothing " +
		"downstream recovers\n# from getting wrong.\nrig:\n")
	fmt.Fprintf(&b, "  amp: %s\n", opts.Amp)

	if opts.Cab != "" {
		fmt.Fprintf(&b, "  cab: %s\n", opts.Cab)
	} else {
		b.WriteString("  # No cabinet named, so the amp's own pairing is " +
			"used — which is what\n  # Line 6 voiced it with.\n")
	}

	b.WriteString(renderPedals(opts.Pedals))

	b.WriteString("\n# How it should sound, in the words a person would " +
		"use. Describe the\n# result, not the control: \"mid-forward\", not " +
		"\"raise the mids\".\ncharacter: []\n\n")

	b.WriteString("# Where this came from, and how far to trust it. `llm` " +
		"means a model\n# asserted it and nobody checked — which is the " +
		"largest correctness risk\n# in this project, so say so rather than " +
		"leaving it implied.\nprovenance:\n")
	b.WriteString("  source: llm\n  confidence: low\n")
	b.WriteString("  notes: >\n    Nothing here has been confirmed against " +
		"a rig rundown, an interview or\n    a recording. Correct it from " +
		"what you hear.\n")

	return b.String()
}

// title names the recipe in its own header comment.
func title(opts NewOptions) string {
	if opts.Band == "" {
		return opts.Name
	}

	return opts.Name + " — " + opts.Band
}

// renderPedals writes the pedal list, in signal order.
func renderPedals(pedals []string) string {
	if len(pedals) == 0 {
		return "  pedals: []\n"
	}

	var b strings.Builder

	b.WriteString("  # In signal order. Order is what the signal does: " +
		"drive ahead of an\n  # amp overdrives its input, drive after it is " +
		"a different sound.\n  pedals:\n")

	for _, p := range pedals {
		fmt.Fprintf(&b, "    - %s\n", p)
	}

	return b.String()
}
