// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	catalog "github.com/retr0h/tonestack/pkg/sdk/catalog"
	chain "github.com/retr0h/tonestack/pkg/sdk/chain"
	compile "github.com/retr0h/tonestack/pkg/sdk/compile"
	corpus "github.com/retr0h/tonestack/pkg/sdk/corpus"
	gen "github.com/retr0h/tonestack/pkg/sdk/rig/gen"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogs is a mock of Catalogs interface.
type MockCatalogs struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogsMockRecorder
	isgomock struct{}
}

// MockCatalogsMockRecorder is the mock recorder for MockCatalogs.
type MockCatalogsMockRecorder struct {
	mock *MockCatalogs
}

// NewMockCatalogs creates a new mock instance.
func NewMockCatalogs(ctrl *gomock.Controller) *MockCatalogs {
	mock := &MockCatalogs{ctrl: ctrl}
	mock.recorder = &MockCatalogsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogs) EXPECT() *MockCatalogsMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockCatalogs) Open(path string) (*catalog.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", path)
	ret0, _ := ret[0].(*catalog.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockCatalogsMockRecorder) Open(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockCatalogs)(nil).Open), path)
}

// MockRecipes is a mock of Recipes interface.
type MockRecipes struct {
	ctrl     *gomock.Controller
	recorder *MockRecipesMockRecorder
	isgomock struct{}
}

// MockRecipesMockRecorder is the mock recorder for MockRecipes.
type MockRecipesMockRecorder struct {
	mock *MockRecipes
}

// NewMockRecipes creates a new mock instance.
func NewMockRecipes(ctrl *gomock.Controller) *MockRecipes {
	mock := &MockRecipes{ctrl: ctrl}
	mock.recorder = &MockRecipesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipes) EXPECT() *MockRecipesMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockRecipes) Find(dir, id string) (gen.RigSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", dir, id)
	ret0, _ := ret[0].(gen.RigSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRecipesMockRecorder) Find(dir, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRecipes)(nil).Find), dir, id)
}

// MockCompiler is a mock of Compiler interface.
type MockCompiler struct {
	ctrl     *gomock.Controller
	recorder *MockCompilerMockRecorder
	isgomock struct{}
}

// MockCompilerMockRecorder is the mock recorder for MockCompiler.
type MockCompilerMockRecorder struct {
	mock *MockCompiler
}

// NewMockCompiler creates a new mock instance.
func NewMockCompiler(ctrl *gomock.Controller) *MockCompiler {
	mock := &MockCompiler{ctrl: ctrl}
	mock.recorder = &MockCompilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompiler) EXPECT() *MockCompilerMockRecorder {
	return m.recorder
}

// Fit mocks base method.
func (m *MockCompiler) Fit(spec chain.Chain, cat *catalog.Catalog, lim chain.Limits) chain.Chain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fit", spec, cat, lim)
	ret0, _ := ret[0].(chain.Chain)
	return ret0
}

// Fit indicates an expected call of Fit.
func (mr *MockCompilerMockRecorder) Fit(spec, cat, lim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fit", reflect.TypeOf((*MockCompiler)(nil).Fit), spec, cat, lim)
}

// Resolve mocks base method.
func (m *MockCompiler) Resolve(spec gen.RigSpec, cat *catalog.Catalog, stats *corpus.Stats) (chain.Chain, []compile.Added, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", spec, cat, stats)
	ret0, _ := ret[0].(chain.Chain)
	ret1, _ := ret[1].([]compile.Added)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Resolve indicates an expected call of Resolve.
func (mr *MockCompilerMockRecorder) Resolve(spec, cat, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockCompiler)(nil).Resolve), spec, cat, stats)
}
