version: 2

project_name: tonestack

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
    binary: tonestack
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/retr0h/tonestack/cmd.version={{.Version}}

archives:
  - formats: [tar.gz]

changelog:
  use: github
  sort: asc

release:
  github:
    owner: retr0h
    name: tonestack
