// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package specdoc

import "errors"

// errNoSchema reports a document that describes no schemas.
var errNoSchema = errors.New("not a RigSpec schema")

// preamble is the part of the page that is about the page.
//
// Everything below it is the contract's own words, so this is the only prose
// anybody has to keep true by hand.
const preamble = `<!-- Generated by internal/specdoc. Do not edit. -->

# The RigSpec grammar

Every field a rig may carry, and what it may say. Generated from
[the contract](../resources/schemas/rigspec.openapi.yaml), so it cannot drift
from what the code actually enforces.

A field marked ` + "`*`" + ` is required. A field that holds another object has
no grammar of its own and shows ` + "`—`" + `; the question moves to that
object's table. Every other field is in one of four buckets:

| grammar | means |
| --- | --- |
| closed | one of a fixed set, listed here and refused if it is not one of them |
| looked up | checked against the catalog for the device in hand, so the valid values depend on which device |
| shaped | checked against a pattern |
| open | prose. Nothing parses it, and nothing will refuse it for what it says |

Reading a rig checks the closed and shaped fields. Building one checks the
looked-up fields as well, because only then is there a catalog to check them
against.
`
