// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	tools "github.com/retr0h/tonestack/pkg/mcp/internal/tools"
	sdk "github.com/retr0h/tonestack/pkg/sdk"
	catalog "github.com/retr0h/tonestack/pkg/sdk/catalog"
	slot "github.com/retr0h/tonestack/pkg/sdk/slot"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockClient) Block(ctx context.Context, id string) (catalog.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", ctx, id)
	ret0, _ := ret[0].(catalog.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Block indicates an expected call of Block.
func (mr *MockClientMockRecorder) Block(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockClient)(nil).Block), ctx, id)
}

// Blocks mocks base method.
func (m *MockClient) Blocks(ctx context.Context, f sdk.Filter) (sdk.Blocks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocks", ctx, f)
	ret0, _ := ret[0].(sdk.Blocks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blocks indicates an expected call of Blocks.
func (mr *MockClientMockRecorder) Blocks(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocks", reflect.TypeOf((*MockClient)(nil).Blocks), ctx, f)
}

// Build mocks base method.
func (m *MockClient) Build(ctx context.Context, recipeID, out string, existing sdk.Existing) (sdk.Made, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", ctx, recipeID, out, existing)
	ret0, _ := ret[0].(sdk.Made)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockClientMockRecorder) Build(ctx, recipeID, out, existing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockClient)(nil).Build), ctx, recipeID, out, existing)
}

// Compile mocks base method.
func (m *MockClient) Compile(ctx context.Context, in sdk.Compile) (sdk.Built, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, in)
	ret0, _ := ret[0].(sdk.Built)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockClientMockRecorder) Compile(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockClient)(nil).Compile), ctx, in)
}

// Devices mocks base method.
func (m *MockClient) Devices(ctx context.Context) (sdk.Attached, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Devices", ctx)
	ret0, _ := ret[0].(sdk.Attached)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Devices indicates an expected call of Devices.
func (mr *MockClientMockRecorder) Devices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Devices", reflect.TypeOf((*MockClient)(nil).Devices), ctx)
}

// ModelMeasurements mocks base method.
func (m *MockClient) ModelMeasurements(ctx context.Context, model string) (sdk.Measured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelMeasurements", ctx, model)
	ret0, _ := ret[0].(sdk.Measured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelMeasurements indicates an expected call of ModelMeasurements.
func (mr *MockClientMockRecorder) ModelMeasurements(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelMeasurements", reflect.TypeOf((*MockClient)(nil).ModelMeasurements), ctx, model)
}

// Open mocks base method.
func (m *MockClient) Open(ctx context.Context) (tools.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx)
	ret0, _ := ret[0].(tools.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockClientMockRecorder) Open(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockClient)(nil).Open), ctx)
}

// Recipe mocks base method.
func (m *MockClient) Recipe(ctx context.Context, id string) (sdk.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recipe", ctx, id)
	ret0, _ := ret[0].(sdk.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recipe indicates an expected call of Recipe.
func (mr *MockClientMockRecorder) Recipe(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recipe", reflect.TypeOf((*MockClient)(nil).Recipe), ctx, id)
}

// Recipes mocks base method.
func (m *MockClient) Recipes(ctx context.Context) (sdk.Recipes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recipes", ctx)
	ret0, _ := ret[0].(sdk.Recipes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recipes indicates an expected call of Recipes.
func (mr *MockClientMockRecorder) Recipes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recipes", reflect.TypeOf((*MockClient)(nil).Recipes), ctx)
}

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSession) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSessionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSession)(nil).Close))
}

// Copy mocks base method.
func (m *MockSession) Copy(ctx context.Context, from, to slot.Address) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, from, to)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Copy indicates an expected call of Copy.
func (mr *MockSessionMockRecorder) Copy(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockSession)(nil).Copy), ctx, from, to)
}

// Export mocks base method.
func (m *MockSession) Export(ctx context.Context, at slot.Address, out string, as sdk.Format, existing sdk.Existing) (sdk.Written, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", ctx, at, out, as, existing)
	ret0, _ := ret[0].(sdk.Written)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export indicates an expected call of Export.
func (mr *MockSessionMockRecorder) Export(ctx, at, out, as, existing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockSession)(nil).Export), ctx, at, out, as, existing)
}

// Import mocks base method.
func (m *MockSession) Import(ctx context.Context, file string, at slot.Address) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, file, at)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockSessionMockRecorder) Import(ctx, file, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockSession)(nil).Import), ctx, file, at)
}

// Preset mocks base method.
func (m *MockSession) Preset(ctx context.Context, at slot.Address) (sdk.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preset", ctx, at)
	ret0, _ := ret[0].(sdk.Reading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preset indicates an expected call of Preset.
func (mr *MockSessionMockRecorder) Preset(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preset", reflect.TypeOf((*MockSession)(nil).Preset), ctx, at)
}

// Presets mocks base method.
func (m *MockSession) Presets(ctx context.Context, setlist int) (sdk.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Presets", ctx, setlist)
	ret0, _ := ret[0].(sdk.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Presets indicates an expected call of Presets.
func (mr *MockSessionMockRecorder) Presets(ctx, setlist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Presets", reflect.TypeOf((*MockSession)(nil).Presets), ctx, setlist)
}

// Select mocks base method.
func (m *MockSession) Select(ctx context.Context, at slot.Address) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, at)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockSessionMockRecorder) Select(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockSession)(nil).Select), ctx, at)
}

// Swap mocks base method.
func (m *MockSession) Swap(ctx context.Context, a, b slot.Address) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Swap", ctx, a, b)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Swap indicates an expected call of Swap.
func (mr *MockSessionMockRecorder) Swap(ctx, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Swap", reflect.TypeOf((*MockSession)(nil).Swap), ctx, a, b)
}
