// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sdk "github.com/retr0h/tonestack/pkg/sdk"
	catalog "github.com/retr0h/tonestack/pkg/sdk/catalog"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Block mocks base method.
func (m *MockClient) Block(catalogPath, id string) (catalog.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", catalogPath, id)
	ret0, _ := ret[0].(catalog.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Block indicates an expected call of Block.
func (mr *MockClientMockRecorder) Block(catalogPath, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockClient)(nil).Block), catalogPath, id)
}

// Blocks mocks base method.
func (m *MockClient) Blocks(catalogPath string, f sdk.Filter) (sdk.Blocks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocks", catalogPath, f)
	ret0, _ := ret[0].(sdk.Blocks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blocks indicates an expected call of Blocks.
func (mr *MockClientMockRecorder) Blocks(catalogPath, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocks", reflect.TypeOf((*MockClient)(nil).Blocks), catalogPath, f)
}

// Build mocks base method.
func (m *MockClient) Build(in sdk.Make) (sdk.Made, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build", in)
	ret0, _ := ret[0].(sdk.Made)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockClientMockRecorder) Build(in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockClient)(nil).Build), in)
}

// Compile mocks base method.
func (m *MockClient) Compile(in sdk.Compile) (sdk.Built, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", in)
	ret0, _ := ret[0].(sdk.Built)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockClientMockRecorder) Compile(in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockClient)(nil).Compile), in)
}

// Copy mocks base method.
func (m *MockClient) Copy(ctx context.Context, in sdk.Edit) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, in)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Copy indicates an expected call of Copy.
func (mr *MockClientMockRecorder) Copy(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockClient)(nil).Copy), ctx, in)
}

// Devices mocks base method.
func (m *MockClient) Devices(ctx context.Context) (sdk.Attached, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Devices", ctx)
	ret0, _ := ret[0].(sdk.Attached)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Devices indicates an expected call of Devices.
func (mr *MockClientMockRecorder) Devices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Devices", reflect.TypeOf((*MockClient)(nil).Devices), ctx)
}

// Export mocks base method.
func (m *MockClient) Export(ctx context.Context, in sdk.Export) (sdk.Written, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", ctx, in)
	ret0, _ := ret[0].(sdk.Written)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export indicates an expected call of Export.
func (mr *MockClientMockRecorder) Export(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockClient)(nil).Export), ctx, in)
}

// Import mocks base method.
func (m *MockClient) Import(ctx context.Context, in sdk.Put) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, in)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockClientMockRecorder) Import(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockClient)(nil).Import), ctx, in)
}

// Measurements mocks base method.
func (m *MockClient) Measurements(in sdk.Corpus) (sdk.Measured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Measurements", in)
	ret0, _ := ret[0].(sdk.Measured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Measurements indicates an expected call of Measurements.
func (mr *MockClientMockRecorder) Measurements(in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Measurements", reflect.TypeOf((*MockClient)(nil).Measurements), in)
}

// Preset mocks base method.
func (m *MockClient) Preset(ctx context.Context, in sdk.Read) (sdk.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preset", ctx, in)
	ret0, _ := ret[0].(sdk.Reading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preset indicates an expected call of Preset.
func (mr *MockClientMockRecorder) Preset(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preset", reflect.TypeOf((*MockClient)(nil).Preset), ctx, in)
}

// Presets mocks base method.
func (m *MockClient) Presets(ctx context.Context, in sdk.Where) (sdk.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Presets", ctx, in)
	ret0, _ := ret[0].(sdk.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Presets indicates an expected call of Presets.
func (mr *MockClientMockRecorder) Presets(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Presets", reflect.TypeOf((*MockClient)(nil).Presets), ctx, in)
}

// Recipe mocks base method.
func (m *MockClient) Recipe(dir, id string) (sdk.Recipe, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recipe", dir, id)
	ret0, _ := ret[0].(sdk.Recipe)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recipe indicates an expected call of Recipe.
func (mr *MockClientMockRecorder) Recipe(dir, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recipe", reflect.TypeOf((*MockClient)(nil).Recipe), dir, id)
}

// Recipes mocks base method.
func (m *MockClient) Recipes(dir string) (sdk.Recipes, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recipes", dir)
	ret0, _ := ret[0].(sdk.Recipes)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recipes indicates an expected call of Recipes.
func (mr *MockClientMockRecorder) Recipes(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recipes", reflect.TypeOf((*MockClient)(nil).Recipes), dir)
}

// Select mocks base method.
func (m *MockClient) Select(ctx context.Context, in sdk.Read) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, in)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockClientMockRecorder) Select(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockClient)(nil).Select), ctx, in)
}

// Swap mocks base method.
func (m *MockClient) Swap(ctx context.Context, in sdk.Edit) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Swap", ctx, in)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Swap indicates an expected call of Swap.
func (mr *MockClientMockRecorder) Swap(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Swap", reflect.TypeOf((*MockClient)(nil).Swap), ctx, in)
}
