// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	preset "github.com/retr0h/tonestack/pkg/sdk/preset"
	slot "github.com/retr0h/tonestack/pkg/sdk/slot"
	gomock "go.uber.org/mock/gomock"
)

// MockDecoder is a mock of Decoder interface.
type MockDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockDecoderMockRecorder
	isgomock struct{}
}

// MockDecoderMockRecorder is the mock recorder for MockDecoder.
type MockDecoderMockRecorder struct {
	mock *MockDecoder
}

// NewMockDecoder creates a new mock instance.
func NewMockDecoder(ctrl *gomock.Controller) *MockDecoder {
	mock := &MockDecoder{ctrl: ctrl}
	mock.recorder = &MockDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecoder) EXPECT() *MockDecoderMockRecorder {
	return m.recorder
}

// Document mocks base method.
func (m *MockDecoder) Document(ctx context.Context, body []byte, at slot.Address, name string) (*preset.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Document", ctx, body, at, name)
	ret0, _ := ret[0].(*preset.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Document indicates an expected call of Document.
func (mr *MockDecoderMockRecorder) Document(ctx, body, at, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Document", reflect.TypeOf((*MockDecoder)(nil).Document), ctx, body, at, name)
}
