// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	catalog "github.com/retr0h/tonestack/pkg/sdk/catalog"
	chain "github.com/retr0h/tonestack/pkg/sdk/chain"
	corpus "github.com/retr0h/tonestack/pkg/sdk/corpus"
	compile "github.com/retr0h/tonestack/pkg/sdk/internal/compile"
	recipes "github.com/retr0h/tonestack/pkg/sdk/internal/recipes"
	preset "github.com/retr0h/tonestack/pkg/sdk/preset"
	rig "github.com/retr0h/tonestack/pkg/sdk/rig"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogs is a mock of Catalogs interface.
type MockCatalogs struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogsMockRecorder
	isgomock struct{}
}

// MockCatalogsMockRecorder is the mock recorder for MockCatalogs.
type MockCatalogsMockRecorder struct {
	mock *MockCatalogs
}

// NewMockCatalogs creates a new mock instance.
func NewMockCatalogs(ctrl *gomock.Controller) *MockCatalogs {
	mock := &MockCatalogs{ctrl: ctrl}
	mock.recorder = &MockCatalogsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogs) EXPECT() *MockCatalogsMockRecorder {
	return m.recorder
}

// Catalog mocks base method.
func (m *MockCatalogs) Catalog(ctx context.Context) (*catalog.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catalog", ctx)
	ret0, _ := ret[0].(*catalog.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Catalog indicates an expected call of Catalog.
func (mr *MockCatalogsMockRecorder) Catalog(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catalog", reflect.TypeOf((*MockCatalogs)(nil).Catalog), ctx)
}

// MockRecipes is a mock of Recipes interface.
type MockRecipes struct {
	ctrl     *gomock.Controller
	recorder *MockRecipesMockRecorder
	isgomock struct{}
}

// MockRecipesMockRecorder is the mock recorder for MockRecipes.
type MockRecipesMockRecorder struct {
	mock *MockRecipes
}

// NewMockRecipes creates a new mock instance.
func NewMockRecipes(ctrl *gomock.Controller) *MockRecipes {
	mock := &MockRecipes{ctrl: ctrl}
	mock.recorder = &MockRecipesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecipes) EXPECT() *MockRecipesMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockRecipes) Find(src recipes.Source, id string) (rig.Spec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", src, id)
	ret0, _ := ret[0].(rig.Spec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRecipesMockRecorder) Find(src, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRecipes)(nil).Find), src, id)
}

// MockCompiler is a mock of Compiler interface.
type MockCompiler struct {
	ctrl     *gomock.Controller
	recorder *MockCompilerMockRecorder
	isgomock struct{}
}

// MockCompilerMockRecorder is the mock recorder for MockCompiler.
type MockCompilerMockRecorder struct {
	mock *MockCompiler
}

// NewMockCompiler creates a new mock instance.
func NewMockCompiler(ctrl *gomock.Controller) *MockCompiler {
	mock := &MockCompiler{ctrl: ctrl}
	mock.recorder = &MockCompilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompiler) EXPECT() *MockCompilerMockRecorder {
	return m.recorder
}

// Controllers mocks base method.
func (m *MockCompiler) Controllers(doc *preset.Document, spec rig.Spec, blocks []chain.Block, cat *catalog.Catalog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Controllers", doc, spec, blocks, cat)
}

// Controllers indicates an expected call of Controllers.
func (mr *MockCompilerMockRecorder) Controllers(doc, spec, blocks, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Controllers", reflect.TypeOf((*MockCompiler)(nil).Controllers), doc, spec, blocks, cat)
}

// Fit mocks base method.
func (m *MockCompiler) Fit(spec chain.Chain, cat *catalog.Catalog, lim chain.Limits) chain.Chain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fit", spec, cat, lim)
	ret0, _ := ret[0].(chain.Chain)
	return ret0
}

// Fit indicates an expected call of Fit.
func (mr *MockCompilerMockRecorder) Fit(spec, cat, lim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fit", reflect.TypeOf((*MockCompiler)(nil).Fit), spec, cat, lim)
}

// Footswitches mocks base method.
func (m *MockCompiler) Footswitches(doc *preset.Document, spec rig.Spec, cat *catalog.Catalog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Footswitches", doc, spec, cat)
}

// Footswitches indicates an expected call of Footswitches.
func (mr *MockCompilerMockRecorder) Footswitches(doc, spec, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Footswitches", reflect.TypeOf((*MockCompiler)(nil).Footswitches), doc, spec, cat)
}

// Lower mocks base method.
func (m *MockCompiler) Lower(doc *preset.Document, spec rig.Spec, cat *catalog.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lower", doc, spec, cat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lower indicates an expected call of Lower.
func (mr *MockCompilerMockRecorder) Lower(doc, spec, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lower", reflect.TypeOf((*MockCompiler)(nil).Lower), doc, spec, cat)
}

// Resolve mocks base method.
func (m *MockCompiler) Resolve(spec rig.Spec, cat *catalog.Catalog, stats *corpus.Stats) (chain.Chain, []compile.Added, []compile.Moved, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", spec, cat, stats)
	ret0, _ := ret[0].(chain.Chain)
	ret1, _ := ret[1].([]compile.Added)
	ret2, _ := ret[2].([]compile.Moved)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Resolve indicates an expected call of Resolve.
func (mr *MockCompilerMockRecorder) Resolve(spec, cat, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockCompiler)(nil).Resolve), spec, cat, stats)
}

// Sections mocks base method.
func (m *MockCompiler) Sections(doc *preset.Document, spec rig.Spec, blocks []chain.Block, cat *catalog.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sections", doc, spec, blocks, cat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sections indicates an expected call of Sections.
func (mr *MockCompilerMockRecorder) Sections(doc, spec, blocks, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sections", reflect.TypeOf((*MockCompiler)(nil).Sections), doc, spec, blocks, cat)
}
