// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	catalog "github.com/retr0h/tonestack/pkg/sdk/catalog"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogs is a mock of Catalogs interface.
type MockCatalogs struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogsMockRecorder
	isgomock struct{}
}

// MockCatalogsMockRecorder is the mock recorder for MockCatalogs.
type MockCatalogsMockRecorder struct {
	mock *MockCatalogs
}

// NewMockCatalogs creates a new mock instance.
func NewMockCatalogs(ctrl *gomock.Controller) *MockCatalogs {
	mock := &MockCatalogs{ctrl: ctrl}
	mock.recorder = &MockCatalogsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogs) EXPECT() *MockCatalogsMockRecorder {
	return m.recorder
}

// Catalog mocks base method.
func (m *MockCatalogs) Catalog(ctx context.Context) (*catalog.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catalog", ctx)
	ret0, _ := ret[0].(*catalog.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Catalog indicates an expected call of Catalog.
func (mr *MockCatalogsMockRecorder) Catalog(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catalog", reflect.TypeOf((*MockCatalogs)(nil).Catalog), ctx)
}
