// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
// Package commanddoc writes the command reference from the CLI itself.
//
// The same tree cobra runs is the one this walks, so the page cannot list a
// flag the tool does not take or miss one it does.
package commanddoc

// preamble is the part of the page that is about the page.
const preamble = `<!-- Generated by cmd/internal/commanddoc. Do not edit. -->

# Commands

Every command and every flag ` + "`tonestack`" + ` takes, generated from the CLI
itself so it cannot drift from what the tool accepts. ` + "`tonestack <command> --help`" + `
prints the same for one command.

For what to do and in what order, see [workflows.md](workflows.md).
`
