// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	catalog "github.com/retr0h/tonestack/pkg/sdk/catalog"
	chain "github.com/retr0h/tonestack/pkg/sdk/chain"
	wire "github.com/retr0h/tonestack/pkg/sdk/internal/wire"
	preset "github.com/retr0h/tonestack/pkg/sdk/preset"
	rig "github.com/retr0h/tonestack/pkg/sdk/rig"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogs is a mock of Catalogs interface.
type MockCatalogs struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogsMockRecorder
	isgomock struct{}
}

// MockCatalogsMockRecorder is the mock recorder for MockCatalogs.
type MockCatalogsMockRecorder struct {
	mock *MockCatalogs
}

// NewMockCatalogs creates a new mock instance.
func NewMockCatalogs(ctrl *gomock.Controller) *MockCatalogs {
	mock := &MockCatalogs{ctrl: ctrl}
	mock.recorder = &MockCatalogsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogs) EXPECT() *MockCatalogsMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockCatalogs) Open(path string) (*catalog.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", path)
	ret0, _ := ret[0].(*catalog.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockCatalogsMockRecorder) Open(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockCatalogs)(nil).Open), path)
}

// MockCompiler is a mock of Compiler interface.
type MockCompiler struct {
	ctrl     *gomock.Controller
	recorder *MockCompilerMockRecorder
	isgomock struct{}
}

// MockCompilerMockRecorder is the mock recorder for MockCompiler.
type MockCompilerMockRecorder struct {
	mock *MockCompiler
}

// NewMockCompiler creates a new mock instance.
func NewMockCompiler(ctrl *gomock.Controller) *MockCompiler {
	mock := &MockCompiler{ctrl: ctrl}
	mock.recorder = &MockCompilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompiler) EXPECT() *MockCompilerMockRecorder {
	return m.recorder
}

// Lift mocks base method.
func (m *MockCompiler) Lift(doc *preset.Document, cat *catalog.Catalog) (rig.Spec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lift", doc, cat)
	ret0, _ := ret[0].(rig.Spec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lift indicates an expected call of Lift.
func (mr *MockCompilerMockRecorder) Lift(doc, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lift", reflect.TypeOf((*MockCompiler)(nil).Lift), doc, cat)
}

// Lower mocks base method.
func (m *MockCompiler) Lower(doc *preset.Document, spec rig.Spec, cat *catalog.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lower", doc, spec, cat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lower indicates an expected call of Lower.
func (mr *MockCompilerMockRecorder) Lower(doc, spec, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lower", reflect.TypeOf((*MockCompiler)(nil).Lower), doc, spec, cat)
}

// MockTranslator is a mock of Translator interface.
type MockTranslator struct {
	ctrl     *gomock.Controller
	recorder *MockTranslatorMockRecorder
	isgomock struct{}
}

// MockTranslatorMockRecorder is the mock recorder for MockTranslator.
type MockTranslatorMockRecorder struct {
	mock *MockTranslator
}

// NewMockTranslator creates a new mock instance.
func NewMockTranslator(ctrl *gomock.Controller) *MockTranslator {
	mock := &MockTranslator{ctrl: ctrl}
	mock.recorder = &MockTranslatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslator) EXPECT() *MockTranslatorMockRecorder {
	return m.recorder
}

// Chain mocks base method.
func (m *MockTranslator) Chain(name string, got wire.DevicePreset, cat *catalog.Catalog) (chain.Chain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chain", name, got, cat)
	ret0, _ := ret[0].(chain.Chain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chain indicates an expected call of Chain.
func (mr *MockTranslatorMockRecorder) Chain(name, got, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chain", reflect.TypeOf((*MockTranslator)(nil).Chain), name, got, cat)
}

// Controllers mocks base method.
func (m *MockTranslator) Controllers(got wire.DevicePreset, cat *catalog.Catalog) *[]rig.Controller {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Controllers", got, cat)
	ret0, _ := ret[0].(*[]rig.Controller)
	return ret0
}

// Controllers indicates an expected call of Controllers.
func (mr *MockTranslatorMockRecorder) Controllers(got, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Controllers", reflect.TypeOf((*MockTranslator)(nil).Controllers), got, cat)
}

// DeviceState mocks base method.
func (m *MockTranslator) DeviceState(got wire.DevicePreset, cat *catalog.Catalog) *rig.DeviceState {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceState", got, cat)
	ret0, _ := ret[0].(*rig.DeviceState)
	return ret0
}

// DeviceState indicates an expected call of DeviceState.
func (mr *MockTranslatorMockRecorder) DeviceState(got, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceState", reflect.TypeOf((*MockTranslator)(nil).DeviceState), got, cat)
}

// Document mocks base method.
func (m *MockTranslator) Document(got wire.DevicePreset, cat *catalog.Catalog, name string) (*preset.Document, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Document", got, cat, name)
	ret0, _ := ret[0].(*preset.Document)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Document indicates an expected call of Document.
func (mr *MockTranslatorMockRecorder) Document(got, cat, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Document", reflect.TypeOf((*MockTranslator)(nil).Document), got, cat, name)
}

// Footswitches mocks base method.
func (m *MockTranslator) Footswitches(got wire.DevicePreset, cat *catalog.Catalog) *[]rig.Footswitch {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Footswitches", got, cat)
	ret0, _ := ret[0].(*[]rig.Footswitch)
	return ret0
}

// Footswitches indicates an expected call of Footswitches.
func (mr *MockTranslatorMockRecorder) Footswitches(got, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Footswitches", reflect.TypeOf((*MockTranslator)(nil).Footswitches), got, cat)
}

// Placements mocks base method.
func (m *MockTranslator) Placements(doc *preset.Document, cat *catalog.Catalog) ([]wire.Placement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Placements", doc, cat)
	ret0, _ := ret[0].([]wire.Placement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Placements indicates an expected call of Placements.
func (mr *MockTranslatorMockRecorder) Placements(doc, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Placements", reflect.TypeOf((*MockTranslator)(nil).Placements), doc, cat)
}

// Snapshots mocks base method.
func (m *MockTranslator) Snapshots(got wire.DevicePreset) *[]rig.Snapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshots", got)
	ret0, _ := ret[0].(*[]rig.Snapshot)
	return ret0
}

// Snapshots indicates an expected call of Snapshots.
func (mr *MockTranslatorMockRecorder) Snapshots(got any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshots", reflect.TypeOf((*MockTranslator)(nil).Snapshots), got)
}
