// Code generated by MockGen. DO NOT EDIT.
// Source: conversation.go
//
// Generated by this command:
//
//	mockgen -source=conversation.go -destination=conversation.gen_test.go -package=device
//

// Package device is a generated GoMock package.
package device

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mocksender is a mock of sender interface.
type Mocksender struct {
	ctrl     *gomock.Controller
	recorder *MocksenderMockRecorder
	isgomock struct{}
}

// MocksenderMockRecorder is the mock recorder for Mocksender.
type MocksenderMockRecorder struct {
	mock *Mocksender
}

// NewMocksender creates a new mock instance.
func NewMocksender(ctrl *gomock.Controller) *Mocksender {
	mock := &Mocksender{ctrl: ctrl}
	mock.recorder = &MocksenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocksender) EXPECT() *MocksenderMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *Mocksender) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MocksenderMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*Mocksender)(nil).Write), p)
}

// Mockreleaser is a mock of releaser interface.
type Mockreleaser struct {
	ctrl     *gomock.Controller
	recorder *MockreleaserMockRecorder
	isgomock struct{}
}

// MockreleaserMockRecorder is the mock recorder for Mockreleaser.
type MockreleaserMockRecorder struct {
	mock *Mockreleaser
}

// NewMockreleaser creates a new mock instance.
func NewMockreleaser(ctrl *gomock.Controller) *Mockreleaser {
	mock := &Mockreleaser{ctrl: ctrl}
	mock.recorder = &MockreleaserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockreleaser) EXPECT() *MockreleaserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Mockreleaser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockreleaserMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Mockreleaser)(nil).Close))
}

// Mockreceiver is a mock of receiver interface.
type Mockreceiver struct {
	ctrl     *gomock.Controller
	recorder *MockreceiverMockRecorder
	isgomock struct{}
}

// MockreceiverMockRecorder is the mock recorder for Mockreceiver.
type MockreceiverMockRecorder struct {
	mock *Mockreceiver
}

// NewMockreceiver creates a new mock instance.
func NewMockreceiver(ctrl *gomock.Controller) *Mockreceiver {
	mock := &Mockreceiver{ctrl: ctrl}
	mock.recorder = &MockreceiverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockreceiver) EXPECT() *MockreceiverMockRecorder {
	return m.recorder
}

// ReadContext mocks base method.
func (m *Mockreceiver) ReadContext(ctx context.Context, p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadContext", ctx, p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadContext indicates an expected call of ReadContext.
func (mr *MockreceiverMockRecorder) ReadContext(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadContext", reflect.TypeOf((*Mockreceiver)(nil).ReadContext), ctx, p)
}
