// Code generated by MockGen. DO NOT EDIT.
// Source: discover_bus.go
//
// Generated by this command:
//
//	mockgen -source=discover_bus.go -destination=discover_bus.gen_test.go -package=device
//

// Package device is a generated GoMock package.
package device

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockbus is a mock of bus interface.
type Mockbus struct {
	ctrl     *gomock.Controller
	recorder *MockbusMockRecorder
	isgomock struct{}
}

// MockbusMockRecorder is the mock recorder for Mockbus.
type MockbusMockRecorder struct {
	mock *Mockbus
}

// NewMockbus creates a new mock instance.
func NewMockbus(ctrl *gomock.Controller) *Mockbus {
	mock := &Mockbus{ctrl: ctrl}
	mock.recorder = &MockbusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockbus) EXPECT() *MockbusMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *Mockbus) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockbusMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Mockbus)(nil).Close))
}

// Devices mocks base method.
func (m *Mockbus) Devices(match func(uint16, uint16) bool) ([]handle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Devices", match)
	ret0, _ := ret[0].([]handle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Devices indicates an expected call of Devices.
func (mr *MockbusMockRecorder) Devices(match any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Devices", reflect.TypeOf((*Mockbus)(nil).Devices), match)
}

// Mockhandle is a mock of handle interface.
type Mockhandle struct {
	ctrl     *gomock.Controller
	recorder *MockhandleMockRecorder
	isgomock struct{}
}

// MockhandleMockRecorder is the mock recorder for Mockhandle.
type MockhandleMockRecorder struct {
	mock *Mockhandle
}

// NewMockhandle creates a new mock instance.
func NewMockhandle(ctrl *gomock.Controller) *Mockhandle {
	mock := &Mockhandle{ctrl: ctrl}
	mock.recorder = &MockhandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockhandle) EXPECT() *MockhandleMockRecorder {
	return m.recorder
}

// Claim mocks base method.
func (m *Mockhandle) Claim() (endpoints, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim")
	ret0, _ := ret[0].(endpoints)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Claim indicates an expected call of Claim.
func (mr *MockhandleMockRecorder) Claim() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*Mockhandle)(nil).Claim))
}

// Close mocks base method.
func (m *Mockhandle) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockhandleMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*Mockhandle)(nil).Close))
}

// Descriptor mocks base method.
func (m *Mockhandle) Descriptor() Descriptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Descriptor")
	ret0, _ := ret[0].(Descriptor)
	return ret0
}

// Descriptor indicates an expected call of Descriptor.
func (mr *MockhandleMockRecorder) Descriptor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Descriptor", reflect.TypeOf((*Mockhandle)(nil).Descriptor))
}

// Mockendpoints is a mock of endpoints interface.
type Mockendpoints struct {
	ctrl     *gomock.Controller
	recorder *MockendpointsMockRecorder
	isgomock struct{}
}

// MockendpointsMockRecorder is the mock recorder for Mockendpoints.
type MockendpointsMockRecorder struct {
	mock *Mockendpoints
}

// NewMockendpoints creates a new mock instance.
func NewMockendpoints(ctrl *gomock.Controller) *Mockendpoints {
	mock := &Mockendpoints{ctrl: ctrl}
	mock.recorder = &MockendpointsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockendpoints) EXPECT() *MockendpointsMockRecorder {
	return m.recorder
}

// In mocks base method.
func (m *Mockendpoints) In() (receiver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "In")
	ret0, _ := ret[0].(receiver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// In indicates an expected call of In.
func (mr *MockendpointsMockRecorder) In() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "In", reflect.TypeOf((*Mockendpoints)(nil).In))
}

// Out mocks base method.
func (m *Mockendpoints) Out() (sender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Out")
	ret0, _ := ret[0].(sender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Out indicates an expected call of Out.
func (mr *MockendpointsMockRecorder) Out() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Out", reflect.TypeOf((*Mockendpoints)(nil).Out))
}
