---
name: Just Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install just
        uses: extractions/setup-just@v4
      - name: Fetch justfiles
        run: just fetch
      - name: Lint justfiles
        run: just just-fmt-check
