---
name: Markdown Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install just
        uses: extractions/setup-just@v4
      - name: Fetch justfiles
        run: just fetch
      - name: Lint markdown
        run: just md-fmt-check
